name: release-picat

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+(-[a-z]{1,5})?"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout changes
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup zig
        uses: mlugg/setup-zig@v2

      - name: run tests
        run: zig build test

      - name: build picat
        run: zig build --release=small

      - name: release picat
        uses: softprops/action-gh-release@v2
        with:
          name: picat-${{ github.ref_name }}
          files: zig-out/bin/picat
          token: ${{ secrets.PICAT_RELEASE_TOKEN }}
          draft: true
